# docker-compose.yml

services:
  db:
    build: ./mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ragnarokroot
      MYSQL_DATABASE: ragnarok
      MYSQL_USER: ragnarok
      MYSQL_PASSWORD: ragnarok

  phpmyadmin:
    labels:
      # Middleware de autenticação:
      - "traefik.http.routers.${COOLIFY_CONTAINER_NAME}-http.middlewares=redirect-to-https,pma-auth@file"
      - "traefik.http.routers.${COOLIFY_CONTAINER_NAME}-https.middlewares=gzip,pma-auth@file"
    image: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ragnarokroot
    depends_on:
      - db

  ragnarok:
    build: ./server
    links:
      - db
    depends_on:
      - db
    tty: true
    stdin_open: true
    ports:
      - "6900:6900"
      - "6121:6121"
      - "5121:5121"
      - "8888:8888"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

  fluxcp:
    build: ./fluxcp
    links:
      - db
      - ragnarok
    depends_on:
      - db
      - ragnarok
    tty: true
    stdin_open: true

  wsproxy:
    build: ./wsproxy
    links:
      - ragnarok
    depends_on:
      - ragnarok
    tty: true
    stdin_open: true
    ports:
      - "5999:5999"

volumes:
  db_data: {}